language: php
php:
  - "5.5"
  - "5.4"
  - "5.3"
before_script: 
  - composer self-update
  - composer install
  - rm -rf report/
script:
  - phpunit --coverage-text --coverage-html report/
after_failure:
after_success:
after_script:
